# Generated by Django 4.2 on 2024-03-07 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='New York Fashion Week', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='El mejor año de la moda', max_length=200)),
                ('body', models.TextField(help_text='El cuerpo del blog, donde se encuentra el contenido principal.')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='La fecha de creación del blog, con valor predeterminado establecido en la fecha y hora actuales.')),
                ('image', models.ImageField(help_text='Una imagen asociada al blog, que se almacenará en la carpeta blog_images/ dentro del directorio de medios de Django.', upload_to='blog_images/')),
                ('author', models.ForeignKey(help_text='El autor del blog, enlazado al modelo de usuario predeterminado de Django.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
